### ISSUE TITLE
Request for Usage Documentation

### ISSUE THREAD

**Issue by fxfitz** [ansible-network/juniper_junos#19]
This seems like something we we would *really* like to utilize on our team, specifically `get_facts` and the pre-built network-engine parser.

Is there any way you could provide some usage instructions?

**Comment by fxfitz** [comment]
Specifically I'm guessing my question is: are there pre-built parser templates within this role to get standard JunOS information?

**Comment by ganeshrn** [comment]
@fxfitz I am currently working on adding pre-built network-engine parser in this role, hopefully, should be available in the upcoming role release. 
Planning to add separate parser file for text and XML format
1) network-engine based command parser for format=text
2) parse_xml (filter) spec parser for format=xml

**Comment by sward1557** [comment]
@ganeshrn Thanks for the information and update. Is there a tentative date for the upcoming role release?

**Comment by ganeshrn** [comment]
@sward1557 The roles repository within `ansible-network` org follows a 2-week release cadence. Refer https://github.com/ansible-network/network-engine/blob/devel/CONTRIBUTING.md#note 
So the next planned release for this role is on 26th Nov 18

**Comment by ganeshrn** [comment]
Fixed by https://github.com/ansible-network/juniper_junos/pull/24
